server:
  port: 1111

# 数据源
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: Zhaoxw2019@
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 100MB

# mybatis支持
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model
  type-mappers-package: com.winter.mapper
  #type-handlers-package: com.winter.handler #必须和@MappedTypes注解配合使用
  #executor-type: batch

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    com.winter.mapper: debug

